trigger:
  - 'master'
pr:
  - '*'
name: $(Date:yyyyMMdd)_Build_$(Rev:r)
pool:
  vmImage: ubuntu-latest
variables:
  - group: Teste
  - name: CONFIGURATION
    value: 'Release'
  - name: RUNTIME
    value: 'linux-musl-x64'
  - name: API_PROJECT_PATH
    value: '**/PocKube.API.csproj'
  - name: TEST_PROJECT_PATH
    value: '**/PocKube.Test.csproj'
steps:
  - task: UseDotNet@2
    displayName: 'dotnet version 8.0'
    inputs:
      packageType: 'sdk'
      version: '8.0.x'
  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: 'restore'
      projects: |
        $(API_PROJECT_PATH)
        $(TEST_PROJECT_PATH)
      restoreArguments: '--ignore-failed-sources --runtime $(RUNTIME)'
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: 'build'
      projects: |
        $(API_PROJECT_PATH)
        $(TEST_PROJECT_PATH)
      arguments: '--configuration $(CONFIGURATION) --runtime $(RUNTIME) --no-restore --no-self-contained'
  - task: DotNetCoreCLI@2
    displayName: 'dotnet test'
    inputs:
      command: 'test'
      projects: '$(TEST_PROJECT_PATH)'
      arguments: '--configuration $(CONFIGURATION) --runtime $(RUNTIME) --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude=[xunit.*]*'
  - task: DotNetCoreCLI@2
    displayName: 'dotnet publish'
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: |
        $(API_PROJECT_PATH)
      arguments: '--configuration $(CONFIGURATION) --runtime $(RUNTIME) --self-contained --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: false
  - task: Docker@2
    displayName: 'docker build and push (stg)'
    inputs:
      containerRegistry: 'John DockerHub'
      repository: 'johnvanderson/poc-kube'
      command: 'buildAndPush'
      dockerfile: '$(Build.SourcesDirectory)/PocKube.API/Dockerfile'
      buildContext: '$(Build.SourcesDirectory)/PocKube.API'
      tags: |
        $(Build.BuildNumber)
        latest

  - task: replacetokens@6
    inputs:
      root: '$(Build.SourcesDirectory)/PocKube.API/Kubernetes'
      sources: |
        configmap.yml
        secret.yml
  
  - task: PublishBuildArtifacts@1
    displayName: 'azdevops publish build artifacts'
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/PocKube.API/Kubernetes'
      ArtifactName: 'poc-kub-api'
      