# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
name: $(Date:yyyyMMdd)_Build_$(Rev:r)
resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerImage: johnvanderson/poc-kube
  BuildConfiguration: 'Release'
  DOTNET_PROJECT_PATH: '**/*PocKube.API.csproj'
  PublishVariant: 'alpine-x64'
pool:
    vmImage: 'ubuntu-latest'
stages:
- stage: CI
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        repository: $(dockerImage)
        dockerfile: '$(Build.SourcesDirectory)/PocKube.API/Dockerfile'
        tags: |
          $(tag)
          latest
    - task: Docker@2
      inputs:
        containerRegistry: 'John DockerHub'
        repository: $(dockerImage)
        command: 'push'
        tags: |
          $(tag)
          latest
    - task: DotNetCoreCLI@2
      displayName: dotnet publish
      inputs:
        command: publish
        publishWebProjects: false
        projects: $(DOTNET_PROJECT_PATH)
        arguments: '--configuration $(BuildConfiguration) --runtime $(PublishVariant) --no-build --output $(Build.ArtifactStagingDirectory) --no-self-contained'      
    - task: PublishBuildArtifacts@1
      displayName: 'poc-kube-publish'
      inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'

