trigger:
  - 'master'
pr:
  - '*'
name: $(Date:yyyyMMdd)_Build_$(Rev:r)
pool:
  vmImage: ubuntu-latest
variables:
  CONFIGURATION: 'Release'
  RUNTIME: 'linux-musl-x64'
  API_PROJECT_PATH: '**/PocKube.API.csproj'
  TEST_PROJECT_PATH: '**/PocKube.Test.csproj'
steps:
  - task: UseDotNet@2
    displayName: 'dotnet version 8.0'
    inputs:
      packageType: 'sdk'
      version: '8.0.x'
  - task: DotNetCoreCLI@2
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')
    displayName: 'dotnet restore (stg)'
    inputs:
      command: 'restore'
      projects: |
        $(API_PROJECT_PATH)
        $(TEST_PROJECT_PATH)
      restoreArguments: '--ignore-failed-sources --runtime $(RUNTIME)'
      feedsToUse: 'config'
      nugetConfigPath: 'nuget.config'
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: 'build'
      projects: |
        $(API_PROJECT_PATH)
        $(TEST_PROJECT_PATH)
      arguments: '--configuration $(CONFIGURATION) --runtime $(RUNTIME) --no-restore --no-self-contained'
  - task: DotNetCoreCLI@2
    displayName: 'dotnet test'
    inputs:
      command: 'test'
      projects: '$(TEST_PROJECT_PATH)'
      arguments: '--configuration $(CONFIGURATION) --runtime $(RUNTIME) --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude=[xunit.*]*'
  - task: DotNetCoreCLI@2
    displayName: 'dotnet publish'
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: |
        $(API_PROJECT_PATH)
      arguments: '--configuration $(CONFIGURATION) --runtime $(RUNTIME) --self-contained --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: false
  - task: Docker@2
    displayName: 'docker build and push (stg)'
    inputs:
      containerRegistry: 'John DockerHub'
      repository: 'johnvanderson/poc-kube'
      command: 'buildAndPush'
      Dockerfile: '$(Build.ArtifactStagingDirectory)/PocKube.API/Dockerfile'
      buildContext: '$(Build.ArtifactStagingDirectory)/PocKube.API.Api'
      tags: |
        $(Build.BuildNumber)
        latest
  - task: PublishBuildArtifacts@1
    displayName: 'azdevops publish build artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/PocKube.API/Kubernetes'
      ArtifactName: 'poc-kub-api'