apiVersion: v1
kind: Secret
metadata:
  name: #{AKS_LABEL}#
  namespace: #{AKS_LABEL}#
  labels:
    app: #{AKS_LABEL}#
type: Opaque
stringData:
  ConnectionStrings__MongoDb: "#{CONNECTIONSTRINGS_MONGODB}#"
