apiVersion: v1
kind: Service
metadata:
  name: #{AKS_LABEL}#
  namespace: #{AKS_LABEL}#
spec:
  type: ClusterIP
  ports:
   - protocol: TCP
     port: #{DOCKER_EXPOSE_PORT}#
     targetPort: 5000
        
  
  selector:
    app: #{AKS_LABEL}#